### ISSUE TITLE
Gofile REST API Endpoints changed

### ISSUE THREAD

**Issue by m0bb1n** [m0bb1n/gofilepy#5]
REST API endpoints changed.  Running the "test_free_functions.py" file throws an immediate error from GofileClient initialization.   Gofile REST API endpoints are still being updated by the developers so wrapper may continue to break in the near future.  Will try to fix issues as they come in.  Current error below.  More will come as gofilepy is getting revamped.

```
Traceback (most recent call last):
  File "/home/m0bb1n/Programs/gofilepy_dev/venv_gofilepy_test/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m0bb1n/Programs/gofilepy_dev/gofilepy/tests/test_free_functions.py", line 9, in <module>
    guest_client = GofileClient()
  File "/home/m0bb1n/Programs/gofilepy_dev/venv_gofilepy_test/lib/python3.10/site-packages/gofilepy/gofile.py", line 34, in __init__
    self.server = GofileClient.get_best_server()
  File "/home/m0bb1n/Programs/gofilepy_dev/venv_gofilepy_test/lib/python3.10/site-packages/gofilepy/gofile.py", line 63, in get_best_server
    return GofileClient.handle_response(resp)['server']
  File "/home/m0bb1n/Programs/gofilepy_dev/venv_gofilepy_test/lib/python3.10/site-packages/gofilepy/gofile.py", line 43, in handle_response
    data = resp.json()
  File "/home/m0bb1n/Programs/gofilepy_dev/venv_gofilepy_test/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
```

**Comment by m0bb1n** [comment]
v0.2.8 is broken.  New version 0.2.9 will be uploaded tomorrow fixing bug.
